/* Replace with your SQL commands */
SET search_path TO lbstarter,public;

CREATE TABLE blog_categories (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  title varchar(200)  NOT NULL ,
  created_on           timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	modified_on          timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	deleted              bool DEFAULT false NOT NULL ,
  CONSTRAINT pk_blog_categories_id PRIMARY KEY ( id ),
  constraint fk_blog_categories_users
     foreign key (user_id)
     REFERENCES users (id)
);
CREATE INDEX idx_blog_categories ON blog_categories ( title );
